[workspace]
resolver = "2"
members = [
    "duvua-framework",
    "duvua-repository",
    "duvua-cache",
    "services/chimera",
    "services/tickets",
    "services/commands",
]

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
