[workspace]
resolver = "2"
members = [
    "libs/framework",
    "libs/repository",
    "libs/cache",
    "services/chimera",
    "services/tickets",
    "services/commands",
    "services/cerberus",
]

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
