x-common:
  bot: &bot-env
    LOG_LEVEL: info

    DISCORD_TOKEN: ""
    DISCORD_GUILD: ""

  postgres: &postgres-env
    POSTGRES_DB: duvua
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: ""

    POSTGRES_MIN_CONNS: 2
    POSTGRES_MAX_CONNS: 32

  player: &player-env
    PLAYER_LISTEN_PORT: 8080
    PLAYER_PASSWORD: ""
    PLAYER_URL: player:8080

    SPOTIFY_CLIENT_ID: ""
    SPOTIFY_CLIENT_SECRET: ""

  davinci: &davinci-env
    WELCOMER_LISTEN_PORT: 8080
    WELCOMER_PASSWORD: ""
    WELCOMER_URL: davinci:8080

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.dockerfile
    command: ["--migrate", "--no-banner"]
    restart: always
    links:
      - player
      - davinci
      - postgres

    environment:
      <<: [*bot-env, *postgres-env, *player-env, *davinci-env]
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  player:
    build:
      context: .
      dockerfile: docker/player.dockerfile
    command: ["--no-banner"]
    restart: always

    environment:
      <<: [*bot-env, *postgres-env, *player-env, *davinci-env]
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  davinci:
    build:
      context: .
      dockerfile: docker/davinci.dockerfile
    command: ["--no-banner"]
    restart: always

    environment:
      <<: [*bot-env, *postgres-env, *player-env, *davinci-env]
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    image: postgres:16
    restart: always

    environment:
      <<: *postgres-env

    volumes:
      - .docker-volumes/postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
