// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/proto/davinci/davinci.proto

package davinci

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Davinci_SendWelcome_FullMethodName = "/davinci.Davinci/SendWelcome"
)

// DavinciClient is the client API for Davinci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DavinciClient interface {
	SendWelcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type davinciClient struct {
	cc grpc.ClientConnInterface
}

func NewDavinciClient(cc grpc.ClientConnInterface) DavinciClient {
	return &davinciClient{cc}
}

func (c *davinciClient) SendWelcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Davinci_SendWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DavinciServer is the server API for Davinci service.
// All implementations must embed UnimplementedDavinciServer
// for forward compatibility.
type DavinciServer interface {
	SendWelcome(context.Context, *WelcomeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDavinciServer()
}

// UnimplementedDavinciServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDavinciServer struct{}

func (UnimplementedDavinciServer) SendWelcome(context.Context, *WelcomeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWelcome not implemented")
}
func (UnimplementedDavinciServer) mustEmbedUnimplementedDavinciServer() {}
func (UnimplementedDavinciServer) testEmbeddedByValue()                 {}

// UnsafeDavinciServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DavinciServer will
// result in compilation errors.
type UnsafeDavinciServer interface {
	mustEmbedUnimplementedDavinciServer()
}

func RegisterDavinciServer(s grpc.ServiceRegistrar, srv DavinciServer) {
	// If the following call pancis, it indicates UnimplementedDavinciServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Davinci_ServiceDesc, srv)
}

func _Davinci_SendWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DavinciServer).SendWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Davinci_SendWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DavinciServer).SendWelcome(ctx, req.(*WelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Davinci_ServiceDesc is the grpc.ServiceDesc for Davinci service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Davinci_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "davinci.Davinci",
	HandlerType: (*DavinciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWelcome",
			Handler:    _Davinci_SendWelcome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/davinci/davinci.proto",
}
