name: Docker

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip')"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Bot docker image metadata
        id: docker_bot_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-bot
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == false }}
            type=ref,event=tag
            type=ref,event=branch

      - name: Player docker image metadata
        id: docker_player_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-player
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == false }}
            type=ref,event=tag
            type=ref,event=branch

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Build Information
        id: build_info
        run: |
          echo "version_tag=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/bot.dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            VERSION=${{ steps.build_info.outputs.version_tag }}
          labels: ${{ steps.docker_bot_meta.outputs.labels }}
          tags: ${{ steps.docker_bot_meta.outputs.tags }}

      - name: Build and Push player
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/player.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.build_info.outputs.version_tag }}
          labels: ${{ steps.docker_player_meta.outputs.labels }}
          tags: ${{ steps.docker_player_meta.outputs.tags }}
