name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Code checkout
        uses: actions/checkout@v4

      - name: Download packages
        run: go mod download

      - name: Build bot
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
          SRC_PATH: github.com/zanz1n/duvua-bot
        run: |
          GOARCH=amd64 make build-bot
          mv bin/duvua-bot bin/duvua-bot-amd64
          chmod 755 bin/duvua-bot-amd64

      - name: Build player
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          SRC_PATH: github.com/zanz1n/duvua-bot
        run: |
          GOARCH=amd64 make build-player
          mv bin/duvua-player bin/duvua-player-amd64
          chmod 755 bin/duvua-player-amd64

          GOARCH=arm64 make build-player
          mv bin/duvua-player bin/duvua-player-arm64
          chmod 755 bin/duvua-player-arm64

      - name: Create checksum
        run: |
          SUM1=`cd bin && sha256sum duvua-bot-amd64`
          SUM2=`cd bin && sha256sum duvua-player-amd64`
          SUM3=`cd bin && sha256sum duvua-player-arm64`
          echo -e "\n#### SHA256 Checksum\n\`\`\`\n$SUM1\n$SUM2\n$SUM3\n\`\`\`\n" >> ./RELEASE_CHANGELOG
          echo -e "$SUM1\n$SUM2\n$SUM3" > checksums.txt

      - name: Create release branch
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "ci@duvua.izan.com.br"
          git config --local user.name "Duvua CI"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/var Version = \".*\"/var Version = \"${REF:11}\"/" config/const.go
          git add config/const.go
          git commit -m "bump version for release"
          git push

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: ./RELEASE_CHANGELOG

      - name: Upload bot amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/duvua-bot-amd64
          asset_name: duvua-bot-amd64
          asset_content_type: application/octet-stream

      - name: Upload player amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/duvua-player-amd64
          asset_name: duvua-player-amd64
          asset_content_type: application/octet-stream

      - name: Upload player arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/duvua-player-arm64
          asset_name: duvua-player-arm64
          asset_content_type: application/octet-stream

      - name: Upload checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain
